### ISSUE TITLE
No such file or directory: '/path/to/Models/c3d-pretrained.pth'

### ISSUE THREAD

**Issue by dreamedrainbow** [jfzhang95/pytorch-video-recognition#31]
when run train.py, I counter the problem followed:
Traceback (most recent call last):
  File "/tmp/pycharm_project_466/train.py", line 202, in <module>
    train_model()
  File "/tmp/pycharm_project_466/train.py", line 61, in train_model
    model = C3D_model.C3D(num_classes=num_classes, pretrained=True)
  File "/tmp/pycharm_project_466/network/C3D_model.py", line 42, in __init__
    self.__load_pretrained_weights()
  File "/tmp/pycharm_project_466/network/C3D_model.py", line 109, in __load_pretrained_weights
    p_dict = torch.load(Path.model_dir())
  File "/home/zhanghao/anaconda3/envs/python35/lib/python3.5/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/Models/c3d-pretrained.pth'
How can I solve it?

**Comment by dreamedrainbow** [comment]
I have solved this problem. If you are troubling, you can point it .

**Comment by santhoshmani888** [comment]
facing same issue. whats the fix
