### ISSUE TITLE
Inference.py question for frame process

### ISSUE THREAD

**Issue by Magsun** [jfzhang95/pytorch-video-recognition#42]
Hello @jfzhang95 , thanks for your share of c3d implement.

When I inference with trained c3d model, I notice that you did some process to central croped frame.

listed here:
![image](https://user-images.githubusercontent.com/12060858/80663407-7a67c480-8ac6-11ea-9121-ce9323924a8c.png)

tmp = tmp_ - np.array([[[90.0, 98.0, 102.0]]])

Kindly help to explain that what purpose of doing this operation.

Thanks again.

**Comment by marsna** [comment]
Can you run inference.py with pretrained model?
I run inference.py and see error:
Traceback (most recent call last):
File "inference.py", line 78, in
main()
File "inference.py", line 32, in main
model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'

**Comment by Magsun** [comment]
> Can you run inference.py with pretrained model?
> I run inference.py and see error:
> Traceback (most recent call last):
> File "inference.py", line 78, in
> main()
> File "inference.py", line 32, in main
> model.load_state_dict(checkpoint['state_dict'])
> KeyError: 'state_dict'

I didn't see this error. My code is here:

    # init model
    model = C3D_model.C3D(num_classes=2)
    checkpoint = torch.load('/workspace/pytorch-video-recognition/run/run_4/models/C3D-ucf101_epoch-3.pth.tar',
                            map_location=lambda storage, loc: storage)
    model.load_state_dict(checkpoint['state_dict'])

**Comment by marsna** [comment]
Thank you very much.I'll try to train my dataset.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Magsun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 上午10:52
收件人:&nbsp;"jfzhang95/pytorch-video-recognition"<pytorch-video-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Mars.Nan"<1664682465@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jfzhang95/pytorch-video-recognition] Inference.py question for frame process (#42)





  
Can you run inference.py with pretrained model?
 I run inference.py and see error:
 Traceback (most recent call last):
 File "inference.py", line 78, in
 main()
 File "inference.py", line 32, in main
 model.load_state_dict(checkpoint['state_dict'])
 KeyError: 'state_dict'
  
I didn't see this error. My code is here:
 # init model model = C3D_model.C3D(num_classes=2) checkpoint = torch.load('/workspace/pytorch-video-recognition/run/run_4/models/C3D-ucf101_epoch-3.pth.tar',                         map_location=lambda storage, loc: storage) model.load_state_dict(checkpoint['state_dict'])
