### ISSUE TITLE
I can't download pretrained model

### ISSUE THREAD

**Issue by anzheng13** [jfzhang95/pytorch-video-recognition#44]

**Comment by anzheng13** [comment]
I download this in windows

**Comment by WENDGOUNDI** [comment]
Use this link
https://drive.google.com/file/d/19NWziHWh1LgCcHU34geoKwYezAogv9fX/view

**Comment by anzheng13** [comment]
Thank you.

**Comment by marsna** [comment]
Can you run inference.py with pretrained model?
I run inference.py and see error:
Traceback (most recent call last):
File "inference.py", line 78, in 
main()
File "inference.py", line 32, in main
model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'

**Comment by laisiewcheng** [comment]
> Use this link
> https://drive.google.com/file/d/19NWziHWh1LgCcHU34geoKwYezAogv9fX/view

May I know this is pretrained using what dataset? Sports1M?

**Comment by skyqwe123** [comment]
> Can you run inference.py with pretrained model?
> I run inference.py and see error:
> Traceback (most recent call last):
> File "inference.py", line 78, in
> main()
> File "inference.py", line 32, in main
> model.load_state_dict(checkpoint['state_dict'])
> KeyError: 'state_dict'

I have a similar problem. Have you solved it？

**Comment by skyqwe123** [comment]
> Can you run inference.py with pretrained model?
> I run inference.py and see error:
> Traceback (most recent call last):
> File "inference.py", line 78, in
> main()
> File "inference.py", line 32, in main
> model.load_state_dict(checkpoint['state_dict'])
> KeyError: 'state_dict'

@marsna 
I have a similar problem. Have you solved it

**Comment by marsna** [comment]
I didn't solve it in the end, even though I asked for help via email.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jfzhang95/pytorch-video-recognition"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 晚上9:13
收件人:&nbsp;"jfzhang95/pytorch-video-recognition"<pytorch-video-recognition@noreply.github.com&gt;;
抄送:&nbsp;"Mars.Nan"<1664682465@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jfzhang95/pytorch-video-recognition] I can't download pretrained model (#44)





  
Can you run inference.py with pretrained model?
 I run inference.py and see error:
 Traceback (most recent call last):
 File "inference.py", line 78, in
 main()
 File "inference.py", line 32, in main
 model.load_state_dict(checkpoint['state_dict'])
 KeyError: 'state_dict'
  
@marsna
 I have a similar problem. Have you solved it

**Comment by skyqwe123** [comment]
> I didn't solve it in the end, even though I asked for help via email.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jfzhang95/pytorch-video-recognition" <notifications@github.com&gt;; 发送时间:&nbsp;2021年3月9日(星期二) 晚上9:13 收件人:&nbsp;"jfzhang95/pytorch-video-recognition"<pytorch-video-recognition@noreply.github.com&gt;; 抄送:&nbsp;"Mars.Nan"<1664682465@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [jfzhang95/pytorch-video-recognition] I can't download pretrained model (#44) Can you run inference.py with pretrained model? I run inference.py and see error: Traceback (most recent call last): File "inference.py", line 78, in main() File "inference.py", line 32, in main model.load_state_dict(checkpoint['state_dict']) KeyError: 'state_dict' @marsna I have a similar problem. Have you solved it — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@marsna  I have solved it, change the code like this, it works for me：
    model = C3D(num_classes=101, pretrained=True)
    model.to(device)
    model.eval()

**Comment by vsumm** [comment]
> model = C3D(num_classes=101, pretrained=True)
> model.to(device)
> model.eval()

@skyqwe123  

Thanks for giving an idea to resolve the state_dict error. you cant use `C3D` directly instead of use 

```
    model = C3D_model.C3D(num_classes=101, pretrained=True)
    model.to(device)
    model.eval()
```

use this in `inference.py`

**Comment by farazBhatti** [comment]
No, it wont work as it will only load random weights. Pretrained model shared is trained on sport dataset with 487 classes
