### ISSUE TITLE
KeyError: 'state_dict'

### ISSUE THREAD

**Issue by marsna** [jfzhang95/pytorch-video-recognition#45]
I run inference.py with pretrained model:
Traceback (most recent call last):
  File "inference.py", line 78, in <module>
    main()
  File "inference.py", line 32, in main
    model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'

**Comment by marsna** [comment]
@jfzhang95 I run inference.py with pretrained model:
Traceback (most recent call last):
File "inference.py", line 78, in 
main()
File "inference.py", line 32, in main
model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'
Help me,please!

**Comment by marsna** [comment]
@sdxass  I run inference.py with pretrained model:
Traceback (most recent call last):
File "inference.py", line 78, in
main()
File "inference.py", line 32, in main
model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'
Help me,please!

**Comment by Sandeep418** [comment]
> @jfzhang95 I run inference.py with pretrained model:
> Traceback (most recent call last):
> File "inference.py", line 78, in
> main()
> File "inference.py", line 32, in main
> model.load_state_dict(checkpoint['state_dict'])
> KeyError: 'state_dict'
> Help me,please!

The weight file shared by @jfzhang95 is trained on Sports-1M dataset,(It have 487 classes)its not on UCF-101,if you want to test inference code. give the sports 1m dataset labels file instead of ucf-101 labels file.
https://github.com/gtoderici/sports-1m-dataset/blob/master/labels.txt
